import getConfig from '@shared/config/public-runtime-config';
import { ROUTE_PARTS_BY_LOCALE } from '@shared/const';
import { Locale } from '@shared/utils/i18n';
import { deburr, kebabCase } from 'es-toolkit/compat';

const { publicRuntimeConfig } = getConfig();

/**
 * Next.js omits the prefix of the default locale, so `/zoeken/...` is the canonical Dutch url,
 * while English urls are prefixed: `/en/search/...`
 * Keep this in sync with the `i18n.defaultLocale` setting in next.config.js
 */
export const DEFAULT_LOCALE = Locale.nl;

/** Used as the name part of a detail page url when an ie-object has no usable name */
export const IE_OBJECT_NAME_SLUG_FALLBACK = 'titel';

/**
 * Converts an ie-object title into the slug that forms the last part of its detail page url.
 * All special characters are replaced by dashes, so that every url for a given object is
 * byte for byte identical no matter where it was generated.
 *
 * The accents are stripped first: the sitemap is generated by hetarchief-proxy with lodash'
 * kebabCase, which deburrs, while es-toolkit' kebabCase keeps accented characters as they are.
 * Without the deburr, "L'Écho de Belgique" would be listed in the sitemap as l-echo-de-belgique
 * but redirect to l-écho-de-belgique, so every crawl of the sitemap would hit a redirect.
 * https://meemoo.atlassian.net/browse/ARC-3363
 */
export function getIeObjectNameSlug(name: string | null | undefined): string {
	return kebabCase(deburr(name || '')) || IE_OBJECT_NAME_SLUG_FALLBACK;
}

/** '' for the default locale, '/en' for the others */
export function getLocalePathPrefix(locale: Locale): string {
	return locale === DEFAULT_LOCALE ? '' : `/${locale}`;
}

/** Prefixes a locale relative path with the locale prefix and the client url */
export function getAbsoluteUrl(locale: Locale, relativePath: string): string {
	return `${publicRuntimeConfig.CLIENT_URL}${getLocalePathPrefix(locale)}${relativePath}`;
}

/**
 * The path of an ie-object detail page, relative to the locale prefix.
 * eg: /zoeken/vrt/abc123/het-journaal (nl) or /search/vrt/abc123/het-journaal (en)
 */
export function getIeObjectDetailPath(
	locale: Locale,
	maintainerSlug: string,
	schemaIdentifier: string,
	name: string | null | undefined
): string {
	return `/${ROUTE_PARTS_BY_LOCALE[locale].search}/${maintainerSlug}/${schemaIdentifier}/${getIeObjectNameSlug(
		name
	)}`;
}

/**
 * The path to use as the `destination` of a server side redirect.
 * Next.js does not add the locale prefix to a getServerSideProps redirect destination, it uses
 * the value verbatim, so the prefix has to be part of the path or the redirect drops the locale.
 * Client side `router.push`/`router.replace` do keep the current locale, so those should use
 * getIeObjectDetailPath instead.
 */
export function getIeObjectDetailRedirectDestination(
	locale: Locale,
	maintainerSlug: string,
	schemaIdentifier: string,
	name: string | null | undefined
): string {
	return `${getLocalePathPrefix(locale)}${getIeObjectDetailPath(locale, maintainerSlug, schemaIdentifier, name)}`;
}

/** The absolute, canonical url of an ie-object detail page for one locale */
export function getIeObjectDetailUrl(
	locale: Locale,
	maintainerSlug: string,
	schemaIdentifier: string,
	name: string | null | undefined
): string {
	return getAbsoluteUrl(
		locale,
		getIeObjectDetailPath(locale, maintainerSlug, schemaIdentifier, name)
	);
}
