import { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

const Example: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Example page</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main style={{ display: 'grid', placeItems: 'center', height: '500px' }}>
				<h1>This is an example page</h1>
				<div>
					<Link href="/">Go back</Link>
				</div>
			</main>
		</div>
	);
};

export default Example;
