import { IeObjectsSearchOperator } from '@shared/types/ie-objects';

// 2-letter for url parsing

export enum FilterProperty {
	CAST = 'CAST',
	CREATED_AT = 'CREATED_AT',
	CREATOR = 'CREATOR',
	DESCRIPTION = 'DESCRIPTION',
	DURATION = 'DURATION',
	GENRE = 'GENRE',
	IDENTIFIER = 'IDENTIFIER',
	KEYWORDS = 'KEYWORDS',
	LANGUAGE = 'LANGUAGE',
	MEDIA_TYPE = 'MEDIA_TYPE',
	MEDIUM = 'MEDIUM',
	OBJECT_TYPE = 'OBJECT_TYPE',
	PUBLISHED_AT = 'PUBLISHED_AT',
	PUBLISHER = 'PUBLISHER',
	RELEASE_DATE = 'RELEASE_DATE',
	RIGHTS = 'RIGHTS',
	SPACIAL_COVERAGE = 'SPACIAL_COVERAGE',
	TEMPORAL_COVERAGE = 'TEMPORAL_COVERAGE',
	THEME = 'THEME',
	TITLE = 'TITLE',
	NEWSPAPER_SERIES_NAME = 'NEWSPAPER_SERIES_NAME',
	LOCATION_CREATED = 'LOCATION_CREATED',
	MENTIONS = 'MENTIONS',
}

export const FILTER_LABEL_VALUE_DELIMITER = '---';

export const isRange = (op?: string): boolean => op === IeObjectsSearchOperator.BETWEEN;
