export enum MetadataProp {
	Carrier = 'drager',
	CreatedAt = 'creatiedatum',
	Creator = 'maker',
	Description = 'beschrijving',
	Duration = 'duurtijd',
	Era = 'tijdsperiode',
	Everything = 'alles',
	Genre = 'genre',
	Language = 'taal',
	Location = 'locatie',
	Mediatype = 'bestandstype',
	PublishedAt = 'uitzenddatum',
	Publisher = 'publisher',
	Title = 'titel',
}
