import { type Locale } from '@shared/utils/i18n';

export type LanguageCode =
	| 'aa'
	| 'ab'
	| 'ae'
	| 'af'
	| 'ak'
	| 'am'
	| 'an'
	| 'ar'
	| 'as'
	| 'av'
	| 'ay'
	| 'az'
	| 'ba'
	| 'be'
	| 'bg'
	| 'bh'
	| 'bi'
	| 'bm'
	| 'bn'
	| 'bo'
	| 'br'
	| 'bs'
	| 'ca'
	| 'ce'
	| 'ch'
	| 'co'
	| 'cr'
	| 'cs'
	| 'cu'
	| 'cv'
	| 'cy'
	| 'da'
	| 'de'
	| 'dv'
	| 'dz'
	| 'ee'
	| 'el'
	| 'en'
	| 'eo'
	| 'es'
	| 'et'
	| 'eu'
	| 'fa'
	| 'ff'
	| 'fi'
	| 'fj'
	| 'fo'
	| 'fr'
	| 'fy'
	| 'ga'
	| 'gd'
	| 'gl'
	| 'gn'
	| 'gu'
	| 'gv'
	| 'ha'
	| 'he'
	| 'hi'
	| 'ho'
	| 'hr'
	| 'ht'
	| 'hu'
	| 'hy'
	| 'hz'
	| 'ia'
	| 'id'
	| 'ie'
	| 'ig'
	| 'ii'
	| 'ik'
	| 'io'
	| 'is'
	| 'it'
	| 'iu'
	| 'ja'
	| 'jv'
	| 'ka'
	| 'kg'
	| 'ki'
	| 'kj'
	| 'kk'
	| 'kl'
	| 'km'
	| 'kn'
	| 'ko'
	| 'kr'
	| 'ks'
	| 'ku'
	| 'kv'
	| 'kw'
	| 'ky'
	| 'la'
	| 'lb'
	| 'lg'
	| 'li'
	| 'ln'
	| 'lo'
	| 'lt'
	| 'lu'
	| 'lv'
	| 'mg'
	| 'mh'
	| 'mi'
	| 'mk'
	| 'ml'
	| 'mn'
	| 'mo'
	| 'mr'
	| 'ms'
	| 'mt'
	| 'my'
	| 'na'
	| 'nb'
	| 'nd'
	| 'ne'
	| 'ng'
	| 'nl'
	| 'nn'
	| 'no'
	| 'nr'
	| 'nv'
	| 'ny'
	| 'oc'
	| 'oj'
	| 'om'
	| 'or'
	| 'os'
	| 'pa'
	| 'pi'
	| 'pl'
	| 'ps'
	| 'pt'
	| 'qu'
	| 'rm'
	| 'rn'
	| 'ro'
	| 'ru'
	| 'rw'
	| 'sa'
	| 'sc'
	| 'sd'
	| 'se'
	| 'sg'
	| 'sh'
	| 'si'
	| 'sk'
	| 'sl'
	| 'sm'
	| 'sn'
	| 'so'
	| 'sq'
	| 'sr'
	| 'ss'
	| 'st'
	| 'su'
	| 'sv'
	| 'sw'
	| 'ta'
	| 'te'
	| 'tg'
	| 'th'
	| 'ti'
	| 'tk'
	| 'tl'
	| 'tn'
	| 'to'
	| 'tr'
	| 'ts'
	| 'tt'
	| 'tw'
	| 'ty'
	| 'ug'
	| 'uk'
	| 'ur'
	| 'uz'
	| 've'
	| 'vi'
	| 'vo'
	| 'wa'
	| 'wo'
	| 'xh'
	| 'yi'
	| 'yo'
	| 'za'
	| 'zh'
	| 'zu';

type LanguageNamesByCode = Record<LanguageCode, string>;

type LanguagesByLocale = Record<Locale, LanguageNamesByCode>;

export const LANGUAGES: LanguagesByLocale = {
	nl: {
		aa: 'Afar',
		ab: 'Abchazisch',
		ae: 'Avestisch',
		af: 'Afrikaans',
		ak: 'Akan',
		am: 'Amhaars',
		an: 'Aragonees',
		ar: 'Arabisch',
		as: 'Assamees',
		av: 'Avaars',
		ay: 'Aymara',
		az: 'Azerbeidzjaans',
		ba: 'Basjkiers',
		be: 'Wit-Russisch',
		bg: 'Bulgaars',
		bh: 'Bihari',
		bi: 'Bislama',
		bm: 'Bambara',
		bn: 'Bengaals',
		bo: 'Tibetaans',
		br: 'Bretons',
		bs: 'Bosnisch',
		ca: 'Catalaans',
		ce: 'Tsjetsjeens',
		ch: 'Chamorro',
		co: 'Corsicaans',
		cr: 'Cree',
		cs: 'Tsjechisch',
		cu: 'Kerkslavisch',
		cv: 'Tsjoevasjisch',
		cy: 'Welsh',
		da: 'Deens',
		de: 'Duits',
		dv: 'Divehi',
		dz: 'Dzongkha',
		ee: 'Ewe',
		el: 'Grieks',
		en: 'Engels',
		eo: 'Esperanto',
		es: 'Spaans',
		et: 'Estisch',
		eu: 'Baskisch',
		fa: 'Perzisch',
		ff: 'Fula',
		fi: 'Fins',
		fj: 'Fijisch',
		fo: 'Faerers',
		fr: 'Frans',
		fy: 'Westerlauwers Fries',
		ga: 'Iers',
		gd: 'Schots-Gaelisch',
		gl: 'Galicisch',
		gn: 'Guaran',
		gu: 'Gujarati',
		gv: 'Manx-Gaelisch',
		ha: 'Hausa',
		he: 'Hebreeuws',
		hi: 'Hindi',
		ho: 'Hiri Motu',
		hr: 'Kroatisch',
		ht: 'Haitiaans Creools',
		hu: 'Hongaars',
		hy: 'Armeens',
		hz: 'Herero',
		ia: 'Interlingua',
		id: 'Indonesisch',
		ie: 'Interlingue',
		ig: 'Igbo',
		ii: 'Yi',
		ik: 'Inupiak',
		io: 'Ido',
		is: 'IJslands',
		it: 'Italiaans',
		iu: 'Inuktitut',
		ja: 'Japans',
		jv: 'Javaans',
		ka: 'Georgisch',
		kg: 'Kongo',
		ki: 'Gikuyu',
		kj: 'Kwanyama',
		kk: 'Kazachs',
		kl: 'Groenlands',
		km: 'Cambodjaans',
		kn: 'Kannada',
		ko: 'Koreaans',
		kr: 'Kanuri',
		ks: 'Kasjmiri',
		ku: 'Koerdisch',
		kv: 'Zurjeens',
		kw: 'Cornisch',
		ky: 'Kirgizisch',
		la: 'Latijn',
		lb: 'Luxemburgs',
		lg: 'Luganda',
		li: 'Limburgs',
		ln: 'Lingala',
		lo: 'Laotiaans',
		lt: 'Litouws',
		lu: 'Luba-Katanga',
		lv: 'Lets',
		mg: 'Plateaumalagasi',
		mh: 'Marshallees',
		mi: 'Maori',
		mk: 'Macedonisch',
		ml: 'Malayalam',
		mn: 'Mongools',
		mo: 'Moldavisch',
		mr: 'Marathi',
		ms: 'Maleis',
		mt: 'Maltees',
		my: 'Birmaans',
		na: 'Nauruaans',
		nb: 'Bokml-Noors',
		nd: 'Noord-Ndebele',
		ne: 'Nepalees',
		ng: 'Ndonga',
		nl: 'Nederlands',
		nn: 'Nynorsk',
		no: 'Noors',
		nr: 'Zuid-Ndebele',
		nv: 'Navajo',
		ny: 'Nyanja',
		oc: 'Occitaans',
		oj: 'Ojibweg',
		om: 'Afaan Oromo',
		or: 'Odia',
		os: 'Ossetisch',
		pa: 'Punjabi',
		pi: 'Pali',
		pl: 'Pools',
		ps: 'Pasjtoe',
		pt: 'Portugees',
		qu: 'Quechua',
		rm: 'Reto-Romaans',
		rn: 'Kirundi',
		ro: 'Roemeens',
		ru: 'Russisch',
		rw: 'Kinyarwanda',
		sa: 'Sanskriet',
		sc: 'Sardijns',
		sd: 'Sindhi',
		se: 'Noord-Samisch',
		sg: 'Sango',
		sh: 'Servo-Kroatisch',
		si: 'Singalees',
		sk: 'Slowaaks',
		sl: 'Sloveens',
		sm: 'Samoaans',
		sn: 'Shona',
		so: 'Somalisch',
		sq: 'Albanees',
		sr: 'Servisch',
		ss: 'Swazi',
		st: 'Zuid-Sotho',
		su: 'Soendanees',
		sv: 'Zweeds',
		sw: 'Swahili',
		ta: 'Tamil',
		te: 'Telugu',
		tg: 'Tadzjieks',
		th: 'Thai',
		ti: 'Tigrinya',
		tk: 'Turkmeens',
		tl: 'Tagalog',
		tn: 'Tswana',
		to: 'Tongaans',
		tr: 'Turks',
		ts: 'Tsonga',
		tt: 'Tataars',
		tw: 'Twi',
		ty: 'Tahitiaans',
		ug: 'Oeigoers',
		uk: 'Oekraïens',
		ur: 'Urdu',
		uz: 'Oezbeeks',
		ve: 'Venda',
		vi: 'Vietnamees',
		vo: 'Volapk',
		wa: 'Waals',
		wo: 'Wolof',
		xh: 'Xhosa',
		yi: 'Jiddisch',
		yo: 'Yoruba',
		za: 'Zhuang',
		zh: 'Chinees',
		zu: 'Zoeloe',
	},
	en: {
		aa: 'Afar',
		ab: 'Abkhazian',
		ae: 'Avestan',
		af: 'Afrikaans',
		ak: 'Akan',
		am: 'Amharic',
		an: 'Aragonese',
		ar: 'Arabic',
		as: 'Assamese',
		av: 'Avaric',
		ay: 'Aymara',
		az: 'Azerbaijani',
		ba: 'Bashkir',
		be: 'Belarusian',
		bg: 'Bulgarian',
		bh: 'Bihari',
		bi: 'Bislama',
		bm: 'Bambara',
		bn: 'Bengali',
		bo: 'Tibetan',
		br: 'Breton',
		bs: 'Bosnian',
		ca: 'Catalan, Valencian',
		ce: 'Chechen',
		ch: 'Chamorro',
		co: 'Corsican',
		cr: 'Cree',
		cs: 'Czech',
		cu: 'Church Slavonic, Old Slavonic, Old Church Slavonic',
		cv: 'Chuvash',
		cy: 'Welsh',
		da: 'Danish',
		de: 'German',
		dv: 'Divehi, Dhivehi, Maldivian',
		dz: 'Dzongkha',
		ee: 'Ewe',
		el: 'Greek, Modern (1453–)',
		en: 'English',
		eo: 'Esperanto',
		es: 'Spanish, Castilian',
		et: 'Estonian',
		eu: 'Basque',
		fa: 'Persian',
		ff: 'Fulah',
		fi: 'Finnish',
		fj: 'Fijian',
		fo: 'Faroese',
		fr: 'French',
		fy: 'Western Frisian',
		ga: 'Irish',
		gd: 'Gaelic, Scottish Gaelic',
		gl: 'Galician',
		gn: 'Guarani',
		gu: 'Gujarati',
		gv: 'Manx',
		ha: 'Hausa',
		he: 'Hebrew',
		hi: 'Hindi',
		ho: 'Hiri Motu',
		hr: 'Croatian',
		ht: 'Haitian, Haitian Creole',
		hu: 'Hungarian',
		hy: 'Armenian',
		hz: 'Herero',
		ia: 'Interlingua (International Auxiliary Language Association)',
		id: 'Indonesian',
		ie: 'Interlingue, Occidental',
		ig: 'Igbo',
		ii: 'Sichuan Yi, Nuosu',
		ik: 'Inupiaq',
		io: 'Ido',
		is: 'Icelandic',
		it: 'Italian',
		iu: 'Inuktitut',
		ja: 'Japanese',
		jv: 'Javanese',
		ka: 'Georgian',
		kg: 'Kongo',
		ki: 'Kikuyu, Gikuyu',
		kj: 'Kuanyama, Kwanyama',
		kk: 'Kazakh',
		kl: 'Kalaallisut, Greenlandic',
		km: 'Cambodian',
		kn: 'Kannada',
		ko: 'Korean',
		kr: 'Kanuri',
		ks: 'Kashmiri',
		ku: 'Kurdish',
		kv: 'Komi',
		kw: 'Cornish',
		ky: 'Kirghiz, Kyrgyz',
		la: 'Latin',
		lb: 'Luxembourgish, Letzeburgesch',
		lg: 'Ganda',
		li: 'Limburgan, Limburger, Limburgish',
		ln: 'Lingala',
		lo: 'Lao',
		lt: 'Lithuanian',
		lu: 'Luba-Katanga',
		lv: 'Latvian',
		mg: 'Malagasy',
		mh: 'Marshallese',
		mi: 'Maori',
		mk: 'Macedonian',
		ml: 'Malayalam',
		mn: 'Mongolian',
		mo: 'Moldavish',
		mr: 'Marathi',
		ms: 'Malay',
		mt: 'Maltese',
		my: 'Burmese',
		na: 'Nauru',
		nb: 'Norwegian Bokmål',
		nd: 'North Ndebele',
		ne: 'Nepali',
		ng: 'Ndonga',
		nl: 'Dutch, Flemish',
		nn: 'Norwegian Nynorsk',
		no: 'Norwegian',
		nr: 'South Ndebele',
		nv: 'Navajo, Navaho',
		ny: 'Chichewa, Chewa, Nyanja',
		oc: 'Occitan',
		oj: 'Ojibwa',
		om: 'Oromo',
		or: 'Oriya',
		os: 'Ossetian, Ossetic',
		pa: 'Punjabi, Panjabi',
		pi: 'Pali',
		pl: 'Polish',
		ps: 'Pashto, Pushto',
		pt: 'Portuguese',
		qu: 'Quechua',
		rm: 'Romansh',
		rn: 'Rundi',
		ro: 'Romanian, Moldavian, Moldovan',
		ru: 'Russian',
		rw: 'Kinyarwanda',
		sa: 'Sanskrit',
		sc: 'Sardinian',
		sd: 'Sindhi',
		se: 'Northern Sami',
		sg: 'Sango',
		sh: 'Serbo-Croatian',
		si: 'Sinhala, Sinhalese',
		sk: 'Slovak',
		sl: 'Slovenian',
		sm: 'Samoan',
		sn: 'Shona',
		so: 'Somali',
		sq: 'Albanian',
		sr: 'Serbian',
		ss: 'Swati',
		st: 'Southern Sotho',
		su: 'Sundanese',
		sv: 'Swedish',
		sw: 'Swahili',
		ta: 'Tamil',
		te: 'Telugu',
		tg: 'Tajik',
		th: 'Thai',
		ti: 'Tigrinya',
		tk: 'Turkmen',
		tl: 'Tagalog',
		tn: 'Tswana',
		to: 'Tonga (Tonga Islands)',
		tr: 'Turkish',
		ts: 'Tsonga',
		tt: 'Tatar',
		tw: 'Twi',
		ty: 'Tahitian',
		ug: 'Uighur, Uyghur',
		uk: 'Ukrainian',
		ur: 'Urdu',
		uz: 'Uzbek',
		ve: 'Venda',
		vi: 'Vietnamese',
		vo: 'Volapük',
		wa: 'Walloon',
		wo: 'Wolof',
		xh: 'Xhosa',
		yi: 'Yiddish',
		yo: 'Yoruba',
		za: 'Zhuang, Chuang',
		zh: 'Chinese',
		zu: 'Zulu',
	},
};
