import { tText } from '@shared/helpers/translate';

import { IconName } from './Icon.types';

export enum IconNamesLight {
	AngleDown = 'angle-down--light',
	AngleLeft = 'angle-left--light',
	AngleRight = 'angle-right--light',
	AngleUp = 'angle-up--light',
	Apple = 'apple--light',
	ArrowDown = 'arrow-down--light',
	ArrowLeft = 'arrow-left--light',
	ArrowRight = 'arrow-right--light',
	ArrowUp = 'arrow-up--light',
	Audio = 'audio--light',
	Book = 'book--light',
	Bookmark = 'bookmark--light',
	Calendar = 'calendar--light',
	Check = 'check--light',
	Clock = 'clock--light',
	Compress = 'compress--light',
	Contact = 'contact--light',
	Copy = 'copy--light',
	Description = 'description--light',
	DotsHorizontal = 'dots-horizontal--light',
	DotsVertical = 'dots-vertical--light',
	Download = 'download--light',
	Edit = 'edit--light',
	Email = 'email--light',
	Exclamation = 'exclamation--light',
	Expand = 'expand--light',
	ExpandLeft = 'expand-left--light',
	ExpandRight = 'expand-right--light',
	Export = 'export--light',
	Extern = 'extern--light',
	FastForward = 'fast-forward--light',
	File = 'file--light',
	Filter = 'filter--light',
	Flag = 'flag--light',
	Forbidden = 'forbidden--light',
	GridView = 'grid-view--light',
	Hide = 'hide--light',
	HotelBell = 'hotel-bell--light',
	Hourglass = 'hourglass--light',
	Image = 'image--light',
	Info = 'info--light',
	Key = 'key--light',
	Link = 'link--light',
	ListView = 'list-view--light',
	Lock = 'lock--light',
	LogIn = 'log-in--light',
	LogOut = 'log-out--light',
	Menu = 'menu--light',
	Minus = 'minus--light',
	MissingFile = 'missing-file--light',
	Newspaper = 'newspaper--light',
	NoAudio = 'no-audio--light',
	NoFile = 'no-file--light',
	NoImage = 'no-image--light',
	NoNewspaper = 'no-newspaper--light',
	NoVideo = 'no-video--light',
	NotAvailable = 'not-available--light',
	Notification = 'notification--light',
	OpenDoor = 'open-door--light',
	Pause = 'pause--light',
	Phone = 'phone--light',
	Play = 'play--light',
	Plus = 'plus--light',
	Question = 'question--light',
	Quotes = 'quotes--light',
	Redo = 'redo--light',
	RelatedObjects = 'related-objects--light',
	Repeat = 'repeat--light',
	Request = 'request--light',
	Rewind = 'rewind--light',
	Scissors = 'scissors--light',
	Search = 'search--light',
	Share = 'share--light',
	Shopping = 'shopping--light',
	Show = 'show--light',
	ShowHalf = 'show-half--light',
	SkipBack = 'skip-back--light',
	SkipForward = 'skip-forward--light',
	Sort = 'sort--light',
	SortDown = 'sort-down--light',
	SortTable = 'sort-table--light',
	SortUp = 'sort-up--light',
	Timer = 'timer--light',
	Times = 'times--light',
	Trash = 'trash--light',
	Undo = 'undo--light',
	Unlock = 'unlock--light',
	Upload = 'upload--light',
	User = 'user--light',
	Video = 'video--light',
	ZoomIn = 'zoom-in--light',
	ZoomOut = 'zoom-out--light',
}

export enum IconNamesSolid {
	Audio = 'audio--solid',
	Bookmark = 'bookmark--solid',
	Copy = 'copy--solid',
	Edit = 'edit--solid',
	FastForward = 'fast-forward--solid',
	Filter = 'filter--solid',
	Hide = 'hide--solid',
	Image = 'image--solid',
	Lock = 'lock--solid',
	MissingFile = 'missing-file--solid',
	Newspaper = 'newspaper--solid',
	Notification = 'notification--solid',
	Pause = 'pause--solid',
	Play = 'play--solid',
	Request = 'request--solid',
	Rewind = 'rewind--solid',
	Share = 'share--solid',
	Shopping = 'shopping--solid',
	Show = 'show--solid',
	SkipBack = 'skip-back--solid',
	SkipForward = 'skip-forward--solid',
	Trash = 'trash--solid',
	Unlock = 'unlock--solid',
	User = 'user--solid',
	Users = 'users--solid',
	Video = 'video--solid',
	ZoomIn = 'zoom-in--solid',
	ZoomOut = 'zoom-out--solid',
}

export enum AlertIconNames {
	Notification = IconNamesLight.Notification,
	User = IconNamesLight.User,
	Question = IconNamesLight.Question,
	Info = IconNamesLight.Info,
	Exclamation = IconNamesLight.Exclamation,
	Key = IconNamesLight.Key,
	Calendar = IconNamesLight.Calendar,
	Book = IconNamesLight.Book,
	AngleRight = IconNamesLight.AngleRight,
}

export const ICON_LIST_CONFIG = (): { value: IconName; label: string }[] => {
	const lightIcons = Object.values(IconNamesLight).map((v: IconNamesLight) => ({
		value: v,
		label: tText(`modules/admin/icons/${v}`),
	}));
	const solidIcons = Object.values(IconNamesSolid).map((v: IconNamesSolid) => ({
		value: v,
		label: tText(`modules/admin/icons/${v}`),
	}));

	return [...lightIcons, ...solidIcons];
};

export const ALERT_ICON_LIST_CONFIG = (): { value: string; label: string; key: string }[] => {
	const alertIcons = Object.keys(AlertIconNames).map((v: string) => ({
		value: v,
		label: tText(`modules/admin/icons/${v}`),
		key: 'alert-icon-' + v,
	}));

	return [...alertIcons];
};
