import { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main style={{ display: 'grid', placeItems: 'center', height: '100vh' }}>
				<h1>Welcome to Het Archief</h1>
				<div>
					<Link href="/example">Go to example</Link>
				</div>
			</main>
		</div>
	);
};

export default Home;
