import { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useState } from 'react';

import Modal from 'modules/shared/components/Modal/Modal';

const Home: NextPage = () => {
	const [modalOpen, setModalOpen] = useState(false);
	return (
		<>
			<div>
				<Head>
					<title>Create Next App</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
				</Head>

				<main style={{ display: 'grid', placeItems: 'center', height: '100vh' }}>
					<h1 onClick={() => setModalOpen(true)}>Welcome to Het Archief</h1>
					<div>
						<Link href="/example">Go to example</Link>
					</div>
				</main>
			</div>

			<Modal isOpen={modalOpen} title="Foo" onClose={() => setModalOpen(false)} />
		</>
	);
};

export default Home;
