export enum QUERY_KEYS {
	getAccessibleReadingRooms = 'getAccessibleReadingRooms',
	getActiveVisitForUserAndSpace = 'getActiveVisitForUserAndSpace',
	getCollectionExport = 'getCollectionExport',
	getCollectionMedia = 'getCollectionMedia',
	getCollections = 'getCollections',
	getMediaExport = 'getMediaExport',
	getMediaFilterOptions = 'getMediaFilterOptions',
	getMediaInfo = 'getMediaInfo',
	getMediaObjects = 'getMediaObjects',
	getMediaRelated = 'getMediaRelated',
	getMediaSimilar = 'getMediaSimilar',
	getMediaTicketUrl = 'getMediaTicketUrl',
	getNavigationItems = 'getNavigationItems',
	getNotifications = 'getNotifications',
	getPeakFile = 'getPeakFile',
	getPendingVisitCountForUserBySlug = 'getPendingVisitCountForUserBySlug',
	getReadingRoomInfo = 'getReadingRoomInfo',
	getReadingRooms = 'getReadingRooms',
	getSpace = 'getSpace',
	getVisit = 'getVisit',
	getVisitAccessStatus = 'getVisitAccessStatus',
	getVisits = 'getVisits',
	getContentPage = 'getContentPage',
}
