export enum QUERY_KEYS {
	getAccessibleVisitorSpaces = 'getAccessibleVisitorSpaces',
	getActiveVisitForUserAndSpace = 'getActiveVisitForUserAndSpace',
	getCollectionExport = 'getCollectionExport',
	getCollectionMedia = 'getCollectionMedia',
	getCollections = 'getCollections',
	getMediaExport = 'getMediaExport',
	getMediaFilterOptions = 'getMediaFilterOptions',
	getIeObjectsInfo = 'getIeObjectsInfo',
	getMediaObjects = 'getMediaObjects',
	getMediaRelated = 'getMediaRelated',
	getMediaSimilar = 'getMediaSimilar',
	getMediaTicketUrl = 'getMediaTicketUrl',
	getNavigationItems = 'getNavigationItems',
	getNotifications = 'getNotifications',
	getPeakFile = 'getPeakFile',
	getPendingVisitCountForUserBySlug = 'getPendingVisitCountForUserBySlug',
	getVisitorSpaceInfo = 'getVisitorSpaceInfo',
	getVisitorSpaces = 'getVisitorSpaces',
	getSpace = 'getSpace',
	getVisit = 'getVisit',
	getVisitAccessStatus = 'getVisitAccessStatus',
	getVisits = 'getVisits',
	getContentPage = 'getContentPage',
	getContentPartners = 'getContentPartners',
}
