export enum QUERY_KEYS {
	getAccessibleReadingRooms = 'getAccessibleReadingRooms',
	getActiveVisitForUserAndSpace = 'getActiveVisitForUserAndSpace',
	getCollectionMedia = 'getCollectionMedia',
	getCollections = 'getCollections',
	getCollectionExport = 'getCollectionExport',
	getMediaInfo = 'getMediaInfo',
	getMediaObjects = 'getMediaObjects',
	getMediaTicketUrl = 'getMediaTicketUrl',
	getMediaSimilar = 'getMediaSimilar',
	getMediaRelated = 'getMediaRelated',
	getMediaExport = 'getMediaExport',
	getNotifications = 'getNotifications',
	getReadingRooms = 'getReadingRooms',
	getReadingRoomInfo = 'getReadingRoomInfo',
	getVisits = 'getVisits',
	getVisit = 'getVisit',
	getSpace = 'getSpace',
	getPendingVisitCountForUserBySlug = 'getPendingVisitCountForUserBySlug',
	getNavigationItems = 'getNavigationItems',
	getPeakFile = 'getPeakFile',
}
