import { type AdminConfig } from '@meemoo/admin-core-ui/dist/client.mjs';

import { type Locale } from '@shared/utils/i18n';

export enum RoutePart {
	accessRequested = 'accessRequested',
	account = 'account',
	visitRequests = 'visitRequests',
	materialRequests = 'materialRequests',
	myMaterialRequests = 'myMaterialRequests',
	faq = 'faq',
	favorites = 'favorites',
	userPolicy = 'userPolicy',
	userManagement = 'userManagement',
	user = 'user',
	permissions = 'permissions',
	translations = 'translations',
	admin = 'admin',
	cpAdmin = 'cpAdmin',
	contentPages = 'contentPages',
	contentPageLabels = 'contentPageLabels',
	cookiePolicy = 'cookiePolicy',
	create = 'create',
	edit = 'edit',
	logout = 'logout',
	myFolders = 'myFolders',
	myHistory = 'myHistory',
	myProfile = 'myProfile',
	navigation = 'navigation',
	notFound = 'notFound',
	settings = 'settings',
	users = 'users',
	visitRequest = 'visitRequest',
	visitorSpaceManagement = 'visitorSpaceManagement',
	visitorSpaces = 'visitorSpaces',
	activeVisitors = 'activeVisitors',
	search = 'search',
	visitors = 'visitors',
	visit = 'visit',
	alerts = 'alerts',
	shareFolder = 'shareFolder',
	kioskConditions = 'kioskConditions',
	newsletter = 'newsletter',
	confirmation = 'confirmation',
	failed = 'failed',
	pid = 'pid',
}

const ROUTE_PARTS_NL: Record<RoutePart, string> = {
	accessRequested: 'toegang-aangevraagd',
	account: 'account',
	activeVisitors: 'actieve-bezoekers',
	admin: 'admin',
	alerts: 'meldingen',
	contentPages: 'content-paginas',
	contentPageLabels: 'content-pagina-labels',
	cookiePolicy: 'cookiebeleid',
	cpAdmin: 'beheer',
	create: 'maak',
	edit: 'bewerk',
	faq: 'vragen',
	favorites: 'favorieten',
	kioskConditions: 'kiosk-voorwaarden',
	logout: 'uitloggen',
	materialRequests: 'materiaalaanvragen',
	myFolders: 'mijn-mappen',
	myHistory: 'mijn-bezoek-historiek',
	myMaterialRequests: 'mijn-materiaalaanvragen',
	myProfile: 'mijn-profiel',
	navigation: 'navigatie',
	notFound: '404',
	permissions: 'permissies',
	search: 'zoeken',
	settings: 'instellingen',
	shareFolder: 'map-delen',
	translations: 'vertalingen',
	user: 'gebruikers',
	userManagement: 'gebruikersbeheer',
	userPolicy: 'gebruiksvoorwaarden',
	users: 'gebruikers',
	visit: 'bezoek',
	visitRequest: 'aanvraag',
	visitRequests: 'toegangsaanvragen',
	visitorSpaceManagement: 'bezoekersruimtesbeheer',
	visitorSpaces: 'bezoekersruimtes',
	visitors: 'bezoekers',
	newsletter: 'nieuwsbrief',
	confirmation: 'bevestiging',
	failed: 'mislukt',
	pid: 'pid',
} as const;

const ROUTE_PARTS_EN: Record<RoutePart, string> = {
	accessRequested: 'access-requested',
	account: 'account',
	activeVisitors: 'active-visitors',
	admin: 'admin',
	alerts: 'alerts',
	contentPages: 'content-pages',
	contentPageLabels: 'content-page-labels',
	cookiePolicy: 'cookie-policy',
	cpAdmin: 'management',
	create: 'create',
	edit: 'edit',
	faq: 'faq',
	favorites: 'favorites',
	kioskConditions: 'kiosk-conditions',
	logout: 'logout',
	materialRequests: 'item-requests',
	myFolders: 'my-folders',
	myHistory: 'my-visit-history',
	myMaterialRequests: 'my-item-requests',
	myProfile: 'my-profile',
	navigation: 'navigation',
	notFound: '404',
	permissions: 'permissions',
	search: 'search',
	settings: 'settings',
	shareFolder: 'folder-share',
	translations: 'translations',
	user: 'users',
	userManagement: 'user-management',
	userPolicy: 'user-conditions',
	users: 'users',
	visit: 'visit',
	visitRequest: 'requests',
	visitRequests: 'visit-requests',
	visitorSpaceManagement: 'manage-local-access',
	visitorSpaces: 'organisations',
	visitors: 'visitors',
	newsletter: 'newsletter',
	confirmation: 'confirmation',
	failed: 'failed',
	pid: 'pid',
} as const;

// Note: Also used to set 'Bezoekersruimtes' active state if url does not start with any of the following prefixes
type RoutePrefix =
	| 'cpAdmin'
	| 'admin'
	| 'account'
	| 'faq'
	| 'userConditions'
	| 'cookiePolicy'
	| 'notFound';

const ROUTE_PREFIXES_NL: Record<RoutePrefix, string> = {
	cpAdmin: ROUTE_PARTS_NL.cpAdmin,
	admin: ROUTE_PARTS_NL.admin,
	account: ROUTE_PARTS_NL.account,
	faq: ROUTE_PARTS_NL.faq,
	userConditions: ROUTE_PARTS_NL.userPolicy,
	cookiePolicy: ROUTE_PARTS_NL.cookiePolicy,
	notFound: ROUTE_PARTS_NL.notFound,
} as const;

const ROUTE_PREFIXES_EN: Record<RoutePrefix, string> = {
	cpAdmin: ROUTE_PARTS_EN.cpAdmin,
	admin: ROUTE_PARTS_EN.admin,
	account: ROUTE_PARTS_EN.account,
	faq: ROUTE_PARTS_EN.faq,
	userConditions: ROUTE_PARTS_EN.userPolicy,
	cookiePolicy: ROUTE_PARTS_EN.cookiePolicy,
	notFound: ROUTE_PARTS_EN.notFound,
} as const;

export enum RouteKey {
	account = 'account',
	accountMyFolders = 'accountMyFolders',
	accountMyMaterialRequests = 'accountMyMaterialRequests',
	accountMyProfile = 'accountMyProfile',
	accountMyVisitHistory = 'accountMyVisitHistory',
	accountShareFolder = 'accountShareFolder',
	admin = 'admin',
	adminActiveVisitors = 'adminActiveVisitors',
	adminAlerts = 'adminAlerts',
	adminContentPages = 'adminContentPages',
	adminContentPageDetail = 'adminContentPageDetail',
	adminContentPageCreate = 'adminContentPageCreate',
	adminContentPageEdit = 'adminContentPageEdit',
	adminContentPageLabels = 'adminContentPageLabels',
	adminContentPageLabelDetail = 'adminContentPageLabelDetail',
	adminContentPageLabelCreate = 'adminContentPageLabelCreate',
	adminContentPageLabelEdit = 'adminContentPageLabelEdit',
	adminMaterialRequests = 'adminMaterialRequests',
	adminNavigationBarOverview = 'adminNavigationBarOverview',
	adminNavigationBarDetail = 'adminNavigationBarDetail',
	adminNavigationItemCreate = 'adminNavigationItemCreate',
	adminNavigationItemEdit = 'adminNavigationItemEdit',
	adminPermissions = 'adminPermissions',
	adminTranslations = 'adminTranslations',
	adminUserManagement = 'adminUserManagement',
	adminUsers = 'adminUsers',
	adminVisitRequests = 'adminVisitRequests',
	adminVisitorSpaceCreate = 'adminVisitorSpaceCreate',
	adminVisitorSpaceEdit = 'adminVisitorSpaceEdit',
	adminVisitorSpaces = 'adminVisitorSpaces',
	cookiePolicy = 'cookiePolicy',
	cpAdmin = 'cpAdmin',
	cpAdminMaterialRequests = 'cpAdminMaterialRequests',
	cpAdminSettings = 'cpAdminSettings',
	cpAdminVisitRequests = 'cpAdminVisitRequests',
	cpAdminVisitors = 'cpAdminVisitors',
	home = 'home',
	logout = 'logout',
	newsletter = 'newsletter',
	newsletterConfirm = 'newsletterConfirm',
	newsletterFailed = 'newsletterFailed',
	notFound = 'notFound',
	search = 'search',
	searchSpace = 'searchSpace',
	userPolicy = 'userPolicy',
	visit = 'visit',
	visitRequested = 'visitRequested',
	visitorSpaceManagement = 'visitorSpaceManagement',
	permalink = 'permalink',
}

const ROUTES_NL: Record<RouteKey, string> = {
	account: `/${ROUTE_PARTS_NL.account}`,
	accountMyFolders: `/${ROUTE_PARTS_NL.account}/${ROUTE_PARTS_NL.myFolders}`,
	accountMyMaterialRequests: `/${ROUTE_PARTS_NL.account}/${ROUTE_PARTS_NL.myMaterialRequests}`,
	accountMyProfile: `/${ROUTE_PARTS_NL.account}/${ROUTE_PARTS_NL.myProfile}`,
	accountMyVisitHistory: `/${ROUTE_PARTS_NL.account}/${ROUTE_PARTS_NL.myHistory}`,
	accountShareFolder: `/${ROUTE_PARTS_NL.account}/${ROUTE_PARTS_NL.shareFolder}/:id`,
	admin: `/${ROUTE_PARTS_NL.admin}`,
	adminActiveVisitors: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.visitorSpaceManagement}/${ROUTE_PARTS_NL.activeVisitors}`,
	adminAlerts: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.alerts}`,
	adminContentPages: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.contentPages}`,
	adminContentPageDetail: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.contentPages}/:id}`,
	adminContentPageCreate: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.contentPages}/${ROUTE_PARTS_NL.create}`,
	adminContentPageEdit: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.contentPages}/:id/${ROUTE_PARTS_NL.edit}`,
	adminContentPageLabels: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.contentPageLabels}`,
	adminContentPageLabelDetail: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.contentPageLabels}/:id`,
	adminContentPageLabelCreate: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.contentPageLabels}/${ROUTE_PARTS_NL.create}`,
	adminContentPageLabelEdit: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.contentPageLabels}/:id/${ROUTE_PARTS_NL.edit}`,
	adminMaterialRequests: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.materialRequests}`,
	adminNavigationBarOverview: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.navigation}`,
	adminNavigationBarDetail: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.navigation}/:navigationBarId`,
	adminNavigationItemCreate: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.navigation}/:navigationBarId/${ROUTE_PARTS_NL.create}`,
	adminNavigationItemEdit: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.navigation}/:navigationBarId/:navigationItemId/${ROUTE_PARTS_NL.edit}`,
	adminPermissions: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.userManagement}/${ROUTE_PARTS_NL.permissions}`,
	adminTranslations: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.translations}`,
	adminUserManagement: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.userManagement}`,
	adminUsers: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.userManagement}/${ROUTE_PARTS_NL.users}`,
	adminVisitRequests: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.visitorSpaceManagement}/${ROUTE_PARTS_NL.visitRequests}`,
	adminVisitorSpaceCreate: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.visitorSpaceManagement}/${ROUTE_PARTS_NL.visitorSpaces}/${ROUTE_PARTS_NL.create}`,
	adminVisitorSpaceEdit: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.visitorSpaceManagement}/${ROUTE_PARTS_NL.visitorSpaces}/:slug`,
	adminVisitorSpaces: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.visitorSpaceManagement}/${ROUTE_PARTS_NL.visitorSpaces}`,
	cookiePolicy: '/' + ROUTE_PARTS_NL.cookiePolicy,
	cpAdmin: `/${ROUTE_PARTS_NL.cpAdmin}`,
	cpAdminMaterialRequests: `/${ROUTE_PARTS_NL.cpAdmin}/${ROUTE_PARTS_NL.materialRequests}`,
	cpAdminSettings: `/${ROUTE_PARTS_NL.cpAdmin}/${ROUTE_PARTS_NL.settings}`,
	cpAdminVisitRequests: `/${ROUTE_PARTS_NL.cpAdmin}/${ROUTE_PARTS_NL.visitRequests}`,
	cpAdminVisitors: `/${ROUTE_PARTS_NL.cpAdmin}/${ROUTE_PARTS_NL.visitors}`,
	home: '/',
	logout: `/${ROUTE_PARTS_NL.logout}`,
	newsletter: `/${ROUTE_PARTS_NL.newsletter}`,
	newsletterConfirm: `/${ROUTE_PARTS_NL.newsletter}/${ROUTE_PARTS_NL.confirmation}`,
	newsletterFailed: `/${ROUTE_PARTS_NL.newsletter}/${ROUTE_PARTS_NL.failed}`,
	notFound: '/404',
	search: `/${ROUTE_PARTS_NL.search}`,
	searchSpace: `/${ROUTE_PARTS_NL.search}/:slug`,
	userPolicy: `/${ROUTE_PARTS_NL.userPolicy}`,
	visit: `/${ROUTE_PARTS_NL.visit}`,
	visitRequested: `/${ROUTE_PARTS_NL.visit}/:slug/${ROUTE_PARTS_NL.accessRequested}`,
	visitorSpaceManagement: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.visitorSpaceManagement}`,
	permalink: `/${ROUTE_PARTS_NL.pid}/:pid`,
} as const;

const ROUTES_EN: Record<RouteKey, string> = {
	account: `/${ROUTE_PARTS_EN.account}`,
	accountMyFolders: `/${ROUTE_PARTS_EN.account}/${ROUTE_PARTS_EN.myFolders}`,
	accountMyMaterialRequests: `/${ROUTE_PARTS_EN.account}/${ROUTE_PARTS_EN.myMaterialRequests}`,
	accountMyProfile: `/${ROUTE_PARTS_EN.account}/${ROUTE_PARTS_EN.myProfile}`,
	accountMyVisitHistory: `/${ROUTE_PARTS_EN.account}/${ROUTE_PARTS_EN.myHistory}`,
	accountShareFolder: `/${ROUTE_PARTS_EN.account}/${ROUTE_PARTS_EN.shareFolder}/:id`,
	admin: `/${ROUTE_PARTS_EN.admin}`,
	adminActiveVisitors: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.visitorSpaceManagement}/${ROUTE_PARTS_EN.activeVisitors}`,
	adminAlerts: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.alerts}`,
	adminContentPages: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.contentPages}`,
	adminContentPageDetail: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.contentPages}/:id}`,
	adminContentPageCreate: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.contentPages}/${ROUTE_PARTS_EN.create}`,
	adminContentPageEdit: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.contentPages}/:id/${ROUTE_PARTS_EN.edit}`,
	adminContentPageLabels: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.contentPageLabels}`,
	adminContentPageLabelDetail: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.contentPageLabels}/:id`,
	adminContentPageLabelCreate: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.contentPageLabels}/${ROUTE_PARTS_EN.create}`,
	adminContentPageLabelEdit: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.contentPageLabels}/:id/${ROUTE_PARTS_EN.edit}`,
	adminMaterialRequests: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.materialRequests}`,
	adminNavigationBarOverview: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.navigation}`,
	adminNavigationBarDetail: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.navigation}/:navigationBarId`,
	adminNavigationItemCreate: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.navigation}/:navigationBarId/${ROUTE_PARTS_EN.create}`,
	adminNavigationItemEdit: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.navigation}/:navigationBarId/:navigationItemId/${ROUTE_PARTS_EN.edit}`,
	adminPermissions: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.userManagement}/${ROUTE_PARTS_EN.permissions}`,
	adminTranslations: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.translations}`,
	adminUserManagement: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.userManagement}`,
	adminUsers: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.userManagement}/${ROUTE_PARTS_EN.users}`,
	adminVisitRequests: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.visitorSpaceManagement}/${ROUTE_PARTS_EN.visitRequests}`,
	adminVisitorSpaceCreate: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.visitorSpaceManagement}/${ROUTE_PARTS_EN.visitorSpaces}/${ROUTE_PARTS_EN.create}`,
	adminVisitorSpaceEdit: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.visitorSpaceManagement}/${ROUTE_PARTS_EN.visitorSpaces}/:slug`,
	adminVisitorSpaces: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.visitorSpaceManagement}/${ROUTE_PARTS_EN.visitorSpaces}`,
	cookiePolicy: '/' + ROUTE_PARTS_EN.cookiePolicy,
	cpAdmin: `/${ROUTE_PARTS_EN.cpAdmin}`,
	cpAdminMaterialRequests: `/${ROUTE_PARTS_EN.cpAdmin}/${ROUTE_PARTS_EN.materialRequests}`,
	cpAdminSettings: `/${ROUTE_PARTS_EN.cpAdmin}/${ROUTE_PARTS_EN.settings}`,
	cpAdminVisitRequests: `/${ROUTE_PARTS_EN.cpAdmin}/${ROUTE_PARTS_EN.visitRequests}`,
	cpAdminVisitors: `/${ROUTE_PARTS_EN.cpAdmin}/${ROUTE_PARTS_EN.visitors}`,
	home: '/',
	logout: `/${ROUTE_PARTS_EN.logout}`,
	newsletter: `/${ROUTE_PARTS_EN.newsletter}`,
	newsletterConfirm: `/${ROUTE_PARTS_EN.newsletter}/${ROUTE_PARTS_EN.confirmation}`,
	newsletterFailed: `/${ROUTE_PARTS_EN.newsletter}/${ROUTE_PARTS_EN.failed}`,
	notFound: '/404',
	search: `/${ROUTE_PARTS_EN.search}`,
	searchSpace: `/${ROUTE_PARTS_EN.search}/:slug`,
	userPolicy: `/${ROUTE_PARTS_EN.userPolicy}`,
	visit: `/${ROUTE_PARTS_EN.visit}`,
	visitRequested: `/${ROUTE_PARTS_EN.visit}/:slug/${ROUTE_PARTS_EN.accessRequested}`,
	visitorSpaceManagement: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.visitorSpaceManagement}`,
	permalink: `/${ROUTE_PARTS_NL.pid}/:pid`,
} as const;

const ADMIN_CORE_ROUTES_NL: AdminConfig['routes'] = {
	ADMIN_ALERTS_OVERVIEW: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.alerts}`,
	ADMIN_CONTENT_PAGE_CREATE: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.contentPages}/${ROUTE_PARTS_NL.create}`,
	ADMIN_CONTENT_PAGE_DETAIL: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.contentPages}/:id`,
	ADMIN_CONTENT_PAGE_EDIT: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.contentPages}/:id/${ROUTE_PARTS_NL.edit}`,
	ADMIN_CONTENT_PAGE_OVERVIEW: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.contentPages}`,
	ADMIN_CONTENT_PAGE_LABEL_CREATE: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.contentPageLabels}/${ROUTE_PARTS_NL.create}`,
	ADMIN_CONTENT_PAGE_LABEL_DETAIL: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.contentPageLabels}/:id`,
	ADMIN_CONTENT_PAGE_LABEL_EDIT: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.contentPageLabels}/:id/${ROUTE_PARTS_NL.edit}`,
	ADMIN_CONTENT_PAGE_LABEL_OVERVIEW: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.contentPageLabels}`,
	ADMIN_NAVIGATION_CREATE: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.navigation}/${ROUTE_PARTS_NL.create}`,
	ADMIN_NAVIGATION_DETAIL: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.navigation}/:navigationBarId`,
	ADMIN_NAVIGATION_ITEM_CREATE: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.navigation}/:navigationBarId/${ROUTE_PARTS_NL.create}`,
	ADMIN_NAVIGATION_ITEM_EDIT: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.navigation}/:navigationBarId/:navigationItemId/${ROUTE_PARTS_NL.edit}`,
	ADMIN_NAVIGATION_OVERVIEW: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.navigation}`,
	ADMIN_TRANSLATIONS_OVERVIEW: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.translations}`,
	ADMIN_USER_DETAIL: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.users}/:id`,
	ADMIN_USER_EDIT: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.users}/:id/${ROUTE_PARTS_NL.edit}`,
	ADMIN_USER_GROUP_CREATE: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.permissions}/${ROUTE_PARTS_NL.create}`,
	ADMIN_USER_GROUP_DETAIL: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.permissions}/:id`,
	ADMIN_USER_GROUP_EDIT: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.permissions}/:id/${ROUTE_PARTS_NL.edit}`,
	ADMIN_USER_GROUP_OVERVIEW: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.permissions}`,
	ADMIN_USER_OVERVIEW: `/${ROUTE_PARTS_NL.admin}/${ROUTE_PARTS_NL.users}`,
	SEARCH: `/${ROUTE_PARTS_NL.search}`,
} as const;

const ADMIN_CORE_ROUTES_EN: AdminConfig['routes'] = {
	ADMIN_ALERTS_OVERVIEW: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.alerts}`,
	ADMIN_CONTENT_PAGE_CREATE: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.contentPages}/${ROUTE_PARTS_EN.create}`,
	ADMIN_CONTENT_PAGE_DETAIL: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.contentPages}/:id`,
	ADMIN_CONTENT_PAGE_EDIT: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.contentPages}/:id/${ROUTE_PARTS_EN.edit}`,
	ADMIN_CONTENT_PAGE_OVERVIEW: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.contentPages}`,
	ADMIN_CONTENT_PAGE_LABEL_CREATE: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.contentPageLabels}/${ROUTE_PARTS_EN.create}`,
	ADMIN_CONTENT_PAGE_LABEL_DETAIL: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.contentPageLabels}/:id`,
	ADMIN_CONTENT_PAGE_LABEL_EDIT: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.contentPageLabels}/:id/${ROUTE_PARTS_EN.edit}`,
	ADMIN_CONTENT_PAGE_LABEL_OVERVIEW: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.contentPageLabels}`,
	ADMIN_NAVIGATION_CREATE: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.navigation}/${ROUTE_PARTS_EN.create}`,
	ADMIN_NAVIGATION_DETAIL: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.navigation}/:navigationBarId`,
	ADMIN_NAVIGATION_ITEM_CREATE: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.navigation}/:navigationBarId/${ROUTE_PARTS_EN.create}`,
	ADMIN_NAVIGATION_ITEM_EDIT: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.navigation}/:navigationBarId/:navigationItemId/${ROUTE_PARTS_EN.edit}`,
	ADMIN_NAVIGATION_OVERVIEW: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.navigation}`,
	ADMIN_TRANSLATIONS_OVERVIEW: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.translations}`,
	ADMIN_USER_DETAIL: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.users}/:id`,
	ADMIN_USER_EDIT: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.users}/:id/${ROUTE_PARTS_EN.edit}`,
	ADMIN_USER_GROUP_CREATE: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.permissions}/${ROUTE_PARTS_EN.create}`,
	ADMIN_USER_GROUP_DETAIL: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.permissions}/:id`,
	ADMIN_USER_GROUP_EDIT: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.permissions}/:id/${ROUTE_PARTS_EN.edit}`,
	ADMIN_USER_GROUP_OVERVIEW: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.permissions}`,
	ADMIN_USER_OVERVIEW: `/${ROUTE_PARTS_EN.admin}/${ROUTE_PARTS_EN.users}`,
	SEARCH: `/${ROUTE_PARTS_EN.search}`,
} as const;

export enum KNOWN_STATIC_ROUTES {
	TermsOfService = '/gebruikersvoorwaarden-tekst',
	aboutTheVisitorTool = '/over-de-bezoekertool',
	Home = '/',
	kioskConditions = '/kiosk-voorwaarden',
}

export const ROUTE_PARTS_BY_LOCALE: Record<Locale, Record<RoutePart, string>> = {
	nl: ROUTE_PARTS_NL,
	en: ROUTE_PARTS_EN,
} as const;

export const ROUTES_BY_LOCALE: Record<Locale, Record<RouteKey, string>> = {
	nl: ROUTES_NL,
	en: ROUTES_EN,
};

export const ADMIN_CORE_ROUTES_BY_LOCALE: Record<Locale, AdminConfig['routes']> = {
	nl: ADMIN_CORE_ROUTES_NL,
	en: ADMIN_CORE_ROUTES_EN,
};

export const ROUTE_PREFIXES_BY_LOCALE: Record<Locale, Record<RoutePrefix, string>> = {
	nl: ROUTE_PREFIXES_NL,
	en: ROUTE_PREFIXES_EN,
};
