export const ROUTE_PARTS = Object.freeze({
	about: 'over-bezoekersruimtes',
	accessRequested: 'toegang-aangevraagd',
	account: 'account',
	visitRequests: 'aanvragen',
	faq: 'faq',
	userPolicy: 'gebruiksvoorwaarden',
	cookiebeleid: 'cookiebeleid',
	userManagement: 'gebruikersbeheer',
	user: 'gebruikers',
	permissions: 'permissies',
	translations: 'vertalingen',
	translationsV2: 'vertalingen-v2',
	admin: 'admin',
	beheer: 'beheer',
	content: 'content',
	cookiePolicy: 'cookiebeleid',
	create: 'maak',
	edit: 'bewerk',
	logout: 'uitloggen',
	myFolders: 'mijn-mappen',
	myHistory: 'mijn-historiek',
	myProfile: 'mijn-profiel',
	navigation: 'navigatie',
	notFound: '404',
	settings: 'instellingen',
	users: 'gebruikers',
	visitRequest: 'aanvraag',
	visitorSpaceManagement: 'bezoekersruimtesbeheer',
	visitorSpaces: 'bezoekersruimtes',
	visitors: 'actieve-bezoekers',
	myMaterialRequests: 'materiaalaanvragen',
});

// Note: Also used to set 'Bezoekersruimtes' active state if url does not start with any of the following prefixes
export const ROUTE_PREFIXES = Object.freeze({
	beheer: ROUTE_PARTS.beheer,
	admin: ROUTE_PARTS.admin,
	account: ROUTE_PARTS.account,
	about: ROUTE_PARTS.about,
	faq: ROUTE_PARTS.faq,
	gebruiksvoorwaarden: ROUTE_PARTS.userPolicy,
	cookiebeleid: ROUTE_PARTS.cookiePolicy,
	notFound: ROUTE_PARTS.notFound,
});

export const ROUTES = Object.freeze({
	home: '/',
	space: '/:slug',
	termsOfService: '/' + ROUTE_PARTS.userPolicy,
	cookiePolicy: '/' + ROUTE_PARTS.cookiePolicy,
	myFolders: `/${ROUTE_PARTS.account}/${ROUTE_PARTS.myFolders}`,
	myHistory: `/${ROUTE_PARTS.account}/${ROUTE_PARTS.myHistory}`,
	visitRequested: `/:slug/${ROUTE_PARTS.accessRequested}`,
	adminEditSpace: `/${ROUTE_PARTS.admin}/${ROUTE_PARTS.visitorSpaceManagement}/${ROUTE_PARTS.visitorSpaces}/:slug`,
	beheerRequests: `/${ROUTE_PARTS.beheer}/${ROUTE_PARTS.visitRequests}`,
});
