pipeline {
	agent {
		kubernetes {
			defaultContainer 'default'
			yaml """
                apiVersion: v1
                kind: Pod
                metadata:
                    labels:
                        component: builder
                        lang: ${getBaseImageName()}
                        app: client
                spec:
                    containers:
                    - name: default
                      image: ${getImageFromDockerfile()}
                      command:
                        - cat
                      tty: true
                      securityContext:
                        runAsUser: 1000
                    - name: oc
                      image: image-registry.openshift-image-registry.svc:5000/ci-cd/py:3.7
                      command:
                        - cat
                      tty: true
                      imagePullPolicy: Always
                    - name: hasura-cli
                      image: hasura/graphql-engine:v2.6.0.cli-migrations-v3
                      command:
                        - cat
                      tty: true
                      imagePullPolicy: Always
            """.stripIndent()
		}
	}
	options {
		timeout(time: 45, unit: 'MINUTES')
		disableConcurrentBuilds()
	}
	environment {
		OC_PROJECT = 'hetarchief-v3'
		BASE_IMG = "${getImageFromDockerfile()}"
		BASE_IMG_NAME = "${getBaseImageName()}"
		OC_URL = 'https://c113-e.private.eu-de.containers.cloud.ibm.com:30227'
		JIRA_URL = 'meemoo.atlassian.net'
		APP_NAME = 'client'
		DEBUG_TOOLS = 'true'
	}

	stages {
		stage('Calculate extra ENV vars') {
			steps {
				container('oc') {
					script {
						env.GIT_SHORT_COMMIT = sh(script: "printf \$(git rev-parse --short ${GIT_COMMIT})", returnStdout: true)
						env.IMAGE_TAG = sh(script: 'git describe --tags || echo latest', returnStdout: true).trim()

						// The name used for the build config based on the image tag
						// Replace '.' with '_' as '.' is not allowed.
						// env.BUILD_CONFIG_NAME = sh(script: 'echo "${IMAGE_TAG}" | sed -r "s/\\./\\-/g"', returnStdout: true)
					}
				}
			}
		}
		stage('Test code') {
			steps {
				container('default') {
					script {
						sh '''#!/bin/bash
                            npm ci --include=dev
                            npm run test:ci
                        '''
					}
				}
			}
		}
		stage('Import images') {

			steps {
				container('oc') {
					script {
						sh '''#!/bin/bash
                            oc project $OC_PROJECT
                            oc import-image $BASE_IMG --confirm
                            oc set image-lookup $BASE_IMG_NAME
                            sleep 3
                        '''
					}
				}
			}
		}

		stage('Build and Deploy INT') {
			when {
				anyOf {
					changeRequest target: 'main'
					changeRequest target: 'master'
					changeRequest target: 'develop'
					changeRequest target: 'development'
				}
			}
			steps {
				container('oc') {
					script {
						sh """#!/bin/bash
							oc -n $OC_PROJECT patch "bc/${APP_NAME}-int" -p "{\\"spec\\":{\\"source\\":{\\"git\\":{\\"ref\\":\\"${GIT_SHORT_COMMIT}\\"}}}}"
							oc -n $OC_PROJECT patch "bc/${APP_NAME}-int" -p "{\\"metadata\\":{\\"annotations\\":{\\"ref\\":\\"${BRANCH_NAME}\\"}}}"
							oc -n $OC_PROJECT patch "bc/${APP_NAME}-int" -p "{\\"metadata\\":{\\"annotations\\":{\\"shortcommit\\":\\"${GIT_SHORT_COMMIT}\\"}}}"
                        """
					}
					startOpenShiftBuild('int', '${BRANCH_NAME}')
				}
			}
			post {
				always {
					script {
						env.BRANCH_NAME = env.CHANGE_BRANCH
					}
					jiraSendDeploymentInfo site: "${JIRA_URL}", environmentId: 'int', environmentName: 'int', environmentType: 'testing'
				}
			}
		}


		stage('Build and Deploy TST') {
			when {
				anyOf { branch 'develop'; branch 'development' }
			}
			steps {
				container('oc') {
					startOpenShiftBuild('tst', '$GIT_SHORT_COMMIT')
				}
			}
			post {
				always {
					jiraSendDeploymentInfo site: "${JIRA_URL}", environmentId: 'tst', environmentName: 'tst', environmentType: 'staging'
				}
			}
		}


		stage('Build and Deploy QAS') {
			when {
				anyOf { branch 'master'; branch 'main' }
			}
			steps {
				container('oc') {
					startOpenShiftBuild('qas', '$GIT_SHORT_COMMIT')
				}
			}
			post {
				always {
					jiraSendDeploymentInfo site: "${JIRA_URL}", environmentId: 'qas', environmentName: 'qas', environmentType: 'staging'
				}
			}
		}
		stage('Build and Deploy PRD') {
			when {
				buildingTag()
			}
			steps {
				container('oc') {
					script {
						sh """#!/bin/bash
							oc -n $OC_PROJECT patch "bc/${APP_NAME}-prd" -p "{\\"spec\\":{\\"source\\":{\\"git\\":{\\"ref\\":\\"${IMAGE_TAG}\\"}}}}"
							oc -n $OC_PROJECT patch "bc/${APP_NAME}-prd" -p "{\\"metadata\\":{\\"annotations\\":{\\"ref\\":\\"${IMAGE_TAG}\\"}}}"
							oc -n $OC_PROJECT patch "bc/${APP_NAME}-prd" -p "{\\"metadata\\":{\\"annotations\\":{\\"shortcommit\\":\\"${GIT_SHORT_COMMIT}\\"}}}"
                        """
					}
					startOpenShiftBuild('prd', '${IMAGE_TAG}')
				}
			}
			post {
				always {
					jiraSendDeploymentInfo site: "${JIRA_URL}", environmentId: 'prd', environmentName: 'prd', environmentType: 'production'
				}
			}
		}
	}
	post {
		success {
			script {
				if (env.BRANCH_NAME.startsWith('PR')) {
					setGitHubBuildStatus('Build', 'SUCCESS')
				}
			}
		}
		failure {
			script {
				if (env.BRANCH_NAME.startsWith('PR')) {
					setGitHubBuildStatus('Build', 'FAILURE')
				}
			}
		}
		always {
			jiraSendBuildInfo site: "${JIRA_URL}"
			container('default') {
				// Archive tets results
				script {
					if (fileExists('./tests/test_results/junit.xml')) {
						junit 'tests/test_results/junit.xml'
					} else {
						echo 'No test results found'
					}
				}
			}
		}
	}
}

static String getImageFromDockerfile() {
	return 'node:24-alpine'
}

static void getBaseImageName() {
	return getImageFromDockerfile().split(':')[0]
}

void setGitHubBuildStatus(String message, String state) {
	step([
		$class            : 'GitHubCommitStatusSetter',
		reposSource       : [$class: 'ManuallyEnteredRepositorySource', url: "${GIT_URL}"],
		commitShaSource   : [$class: 'ManuallyEnteredShaSource', sha: "${GIT_COMMIT}"],
		errorHandlers     : [[$class: 'ChangingBuildStatusErrorHandler', result: 'UNSTABLE']],
		statusResultSource: [$class: 'ConditionalStatusResultSource', results: [[$class: 'AnyBuildResult', message: message, state: state]]]
	])
}

String getAllCommitsBetweenTags(String from, String to) {
	commit_messages = sh(script: "git log ${from}...${to} --merges --format=%b", returnStdout: true)

	return commit_messages
}

void startOpenShiftBuild(String environment, String dockerTag) {
		sh """#!/bin/bash
		oc project $OC_PROJECT
		oc start-build --follow=true --wait=true $APP_NAME-${environment}
		# Check the status of the rollout
		oc rollout status deployment/$APP_NAME-${environment} --watch=true --timeout=20m

		# Tag with the revision for rollback purposes
		oc tag $APP_NAME:${environment} $APP_NAME:${dockerTag}
	"""
}

void loadEnvironmentVariablesFromFile(String path) {
	def file = readFile(path)
	file.split('\n').each { envLine ->
		def (key, value) = envLine.tokenize('=')
		env."${key}" = "${value}"
	}
}
