#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


# package.json should not contain locally installed packages
if  grep -q "file:../../" "./package.json" ; then
	echo "ui/package.json should not contain any locally installed files. eg: \"@meemoo/react-components\": \"file:../../react-components\""
	exit 1;
else
	exit 0;
fi


# package-lock.json should not contain locally installed packages
if  grep -q "file:../../" "./package-lock.json" ; then
	echo "ui/package.json should not contain any locally installed files. eg: \"@meemoo/react-components\": \"file:../../react-components\""
	exit 1;
else
	exit 0;
fi

# check typescript errors
npm run type-check

# Check linting of the staged files
npx lint-staged
